# Generated by Django 6.0.1 on 2026-01-28 10:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=200)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('primary_color', models.CharField(default='#e63946', help_text='Couleur principale', max_length=7)),
                ('secondary_color', models.CharField(default='#d62828', help_text='Couleur secondaire', max_length=7)),
                ('accent_color', models.CharField(default='#f4a261', help_text="Couleur d'accent", max_length=7)),
                ('background_color', models.CharField(default='#f8f9fa', help_text='Couleur de fond', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', help_text='Couleur du texte sur fond primaire', max_length=7)),
                ('text_dark', models.CharField(default='#1a1a1a', help_text='Couleur du texte principal', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bank_logos/')),
                ('website', models.URLField(blank=True)),
                ('swift_code', models.CharField(blank=True, max_length=11)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Compte Courant'), ('SAVINGS', 'Compte Épargne')], default='CHECKING', max_length=20)),
                ('currency', models.CharField(choices=[('EUR', '€ Euro'), ('USD', '$ Dollar US'), ('GBP', '£ Livre Sterling'), ('CHF', 'CHF Franc Suisse'), ('JPY', '¥ Yen Japonais'), ('CNY', '¥ Yuan Chinois'), ('CAD', '$ Dollar Canadien'), ('AUD', '$ Dollar Australien'), ('INR', '₹ Roupie Indienne'), ('BRL', 'R$ Real Brésilien'), ('SAR', 'ر.س Riyal Saoudien'), ('AED', 'د.إ Dirham Émirati'), ('SGD', '$ Dollar Singapourien')], default='EUR', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('bic', models.CharField(default='MABANFRPPXXX', max_length=11)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('CLOSED', 'Fermé')], default='ACTIVE', max_length=20)),
                ('suspension_reason', models.TextField(blank=True, help_text='Motif de la suspension du compte')),
                ('unblock_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais de déblocage en €', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banking.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['-is_favorite', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], default='DEBIT', max_length=10)),
                ('card_network', models.CharField(choices=[('MASTERCARD', 'Mastercard'), ('VISA', 'Visa')], default='MASTERCARD', max_length=20)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='banking.bankaccount')),
            ],
            options={
                'verbose_name': 'Carte bancaire',
                'verbose_name_plural': 'Cartes bancaires',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TRANSACTION', 'Transaction'), ('SECURITY', 'Sécurité'), ('INFO', 'Information'), ('ALERT', 'Alerte')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('TRANSFER', 'Virement'), ('PAYMENT', 'Paiement de facture'), ('PURCHASE', 'Achat TPV'), ('ONLINE_PURCHASE', 'Achat en ligne')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('recipient_iban', models.CharField(blank=True, max_length=34)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complétée'), ('FAILED', 'Échouée'), ('CANCELLED', 'Annulée')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('rewards_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
