# Generated by Django 6.0.1 on 2026-01-28 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ACCOUNT_SUSPENDED', 'Compte Suspendu'), ('ACCOUNT_UNBLOCKED', 'Compte Débloqué'), ('TRANSACTION', 'Transaction'), ('SECURITY', 'Sécurité'), ('INFO', 'Information'), ('ALERT', 'Alerte'), ('ADMIN', 'Message Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is_staff', models.BooleanField(default=False, help_text="True si envoyé par l'admin")),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Support',
                'verbose_name_plural': 'Messages Support',
                'ordering': ['created_at'],
            },
        ),
    ]
