# Generated by Django 6.0.1 on 2026-01-28 11:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_notification_notification_type_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rejection_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais de rejet en devise du compte', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motif du rejet de la transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Confirmée'), ('REJECTED', 'Rejetée'), ('FAILED', 'Échouée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20),
        ),
    ]
