# Generated by Django 6.0.1 on 2026-01-28 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_transaction_confirmed_at_transaction_rejected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Bordereau de Transaction'), ('REJECTION', 'Document de Rejet'), ('RIB', "Relevé d'Identité Bancaire"), ('STATEMENT', 'Relevé de Compte')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents_pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='banking.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document PDF',
                'verbose_name_plural': 'Documents PDF',
                'ordering': ['-created_at'],
            },
        ),
    ]
