# Generated by Django 6.0.1 on 2026-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(help_text='Email pour recevoir les notifications de virement', max_length=254),
        ),
    ]
