# Generated by Django 6.0.4 on 2026-04-14 18:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_increase_decimal_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL de la page de login (généré automatiquement)', max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='AccountCreationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='France', max_length=100)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('temp_password', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('create_checking', models.BooleanField(default=True)),
                ('initial_checking_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('create_savings', models.BooleanField(default=False)),
                ('initial_savings_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Actif — 45 000 FCFA'), ('SUSPENDED', 'Suspendu — 35 000 FCFA')], default='ACTIVE', max_length=20)),
                ('suspension_reason', models.TextField(blank=True)),
                ('creation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=20)),
                ('geniuspay_reference', models.CharField(blank=True, max_length=100)),
                ('geniuspay_transaction_id', models.IntegerField(blank=True, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=600)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('PENDING_PAYMENT', 'En attente de paiement'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING_PAYMENT', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_orders', to='banking.bank')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande de création de compte',
                'verbose_name_plural': 'Commandes de création de compte',
                'ordering': ['-created_at'],
            },
        ),
    ]
