# Generated by Django 6.0.4 on 2026-04-14 22:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_bank_slug_accountcreationorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreationorder',
            name='deblocage_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant que le client devra payer pour activer son compte suspendu', max_digits=10, verbose_name='Frais de déblocage'),
        ),
    ]
